### ISSUE TITLE
SQLITE_ERRORs on 1.0.4 RC 1

### ISSUE THREAD

**Issue by lasersocks** [BlueBubblesApp/BlueBubbles-Desktop-App#186]
Trying the deb version of 1.0.4 RC1 on up to date Ubuntu and seeing a bunch of SQLITE_ERROR errors in the terminal.
The app does not populate any of the contacts or chats. 1.0.3 does not have these issues for me.

Synced 117 of 615 messages
Failed to save message, [3993E76C-A006-4624-98E8-94EAF047ECAB]
QueryFailedError: SQLITE_ERROR: no such table: chat
    at new QueryFailedError (/opt/BlueBubbles/resources/app.asar/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at handler (/opt/BlueBubbles/resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:76:38)
    at replacement (/opt/BlueBubbles/resources/app.asar/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/opt/BlueBubbles/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:14:21) {

Synced 119 of 615 messages
Failed to save message, [D3A672B6-DE2C-4180-AA9D-CE5F7F899D7A]
QueryFailedError: SQLITE_ERROR: no such table: chat
    at new QueryFailedError (/opt/BlueBubbles/resources/app.asar/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at handler (/opt/BlueBubbles/resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:76:38)
    at replacement (/opt/BlueBubbles/resources/app.asar/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/opt/BlueBubbles/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:14:21) {
  errno: 1,

Error occurred in handler for 'get-chats': QueryFailedError: SQLITE_ERROR: no such table: chat
    at new QueryFailedError (/opt/BlueBubbles/resources/app.asar/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at handler (/opt/BlueBubbles/resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:76:38)
    at replacement (/opt/BlueBubbles/resources/app.asar/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/opt/BlueBubbles/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:14:21) {

etc.

**Comment by zlshames** [comment]
@lasersocks This was due to changes to the DB in the release candidate. Can you please follow these steps exactly to fix the issue:

1. Remove your BlueBubbles Desktop App
2. Delete the app's folder from `~/.config`
3. Download the latest release candidate v1.0.4 (RC 1)
4. Install that version
5. Run that version

The reason this works is because by deleting the app folder, it deletes the database. When you reinstall the release candidate, it will re-create the databases and do a full re-sync

**Comment by zlshames** [comment]
To correct what I said above to not sound like an ass... The issue is on purpose. The v1.0.4 update makes DB changes that can't be migrated. A full reinstall fixes the issues
